'use client';

import { jsPDF } from 'jspdf';
import Image from 'next/image';

interface TranscriptMessage {
    role: string;
    content: string;
    timestamp?: string;
}

interface ExportButtonProps {
    sessionId: string;
    sessionDate: string;
    mentorName: string;
    subject: string;
    topic: string;
    transcript: TranscriptMessage[];
    disabled?: boolean;
}

const ExportButton = ({
    sessionId,
    sessionDate,
    mentorName,
    subject,
    topic,
    transcript,
    disabled = false
}: ExportButtonProps) => {

    const generatePDF = () => {
        if (!transcript || transcript.length === 0) {
            alert('No transcript available for this session.');
            return;
        }

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        const maxWidth = pageWidth - (margin * 2);
        let yPosition = margin;

        const checkPageBreak = (requiredSpace: number) => {
            if (yPosition + requiredSpace > pageHeight - margin) {
                doc.addPage();
                yPosition = margin;
                return true;
            }
            return false;
        };

        doc.setFillColor(216, 170, 132);
        doc.rect(0, 0, pageWidth, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('Mentor Session Transcript', margin, 25);

        yPosition = 50;

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Session Details', margin, yPosition);
        yPosition += 8;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);

        const dateFormatted = new Date(sessionDate).toLocaleString('en-US', {
            dateStyle: 'long',
            timeStyle: 'short'
        });

        doc.text(`Date: ${dateFormatted}`, margin, yPosition);
        yPosition += 6;
        doc.text(`Mentor: ${mentorName}`, margin, yPosition);
        yPosition += 6;
        doc.text(`Subject: ${subject}`, margin, yPosition);
        yPosition += 6;
        doc.text(`Topic: ${topic}`, margin, yPosition);
        yPosition += 6;
        doc.text(`Session ID: ${sessionId}`, margin, yPosition);
        yPosition += 15;

        doc.setDrawColor(216, 170, 132);
        doc.setLineWidth(0.5);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 10;

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Conversation Transcript', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(10);

        const chronologicalTranscript = [...transcript].reverse();

        chronologicalTranscript.forEach((message, index) => {
            const isUser = message.role === 'user';
            const speaker = isUser ? 'You' : mentorName;

            let timeStr = '';
            if (message.timestamp) {
                const time = new Date(message.timestamp);
                timeStr = time.toLocaleTimeString('en-US', {
                    hour: '2-digit',
                    minute: '2-digit'
                });
            }

            checkPageBreak(20);
            doc.setFont('helvetica', 'bold');
            if (isUser) {
                doc.setTextColor(41, 128, 185);
            } else {
                doc.setTextColor(216, 170, 132);
            }
            const headerText = `${speaker}${timeStr ? ` - ${timeStr}` : ''}:`;
            doc.text(headerText, margin, yPosition);
            yPosition += 6;

            doc.setFont('helvetica', 'normal');
            doc.setTextColor(60, 60, 60);

            const lines = doc.splitTextToSize(message.content, maxWidth - 5);

            lines.forEach((line: string) => {
                checkPageBreak(6);
                doc.text(line, margin + 5, yPosition);
                yPosition += 5;
            });

            yPosition += 5;
        });

        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.setFont('helvetica', 'italic');
            const footerText = `Page ${i} of ${totalPages} | Generated by Mentor Platform`;
            const footerWidth = doc.getTextWidth(footerText);
            doc.text(footerText, (pageWidth - footerWidth) / 2, pageHeight - 10);
        }

        const dateStr = new Date(sessionDate).toISOString().split('T')[0];
        const filename = `mentor-transcript-${subject}-${dateStr}.pdf`;

        doc.save(filename);
    };

    if (!transcript || transcript.length === 0) {
        return null;
    }

    return (
        <button
            onClick={generatePDF}
            disabled={disabled}
            className="export-btn"
            title="Export transcript as PDF"
        >
            <Image
                src="/icons/download.svg"
                alt="Export PDF"
                width={18}
                height={18}
            />
            <span className="max-md:hidden">Export PDF</span>
        </button>
    );
};

export default ExportButton;
